// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZimENmiHF1BqdNvbOxuNjETSWH7GOcw',
    appId: '1:239580414059:web:07388637b5d9bb1d36312e',
    messagingSenderId: '239580414059',
    projectId: 'miupcv3',
    authDomain: 'miupcv3.firebaseapp.com',
    storageBucket: 'miupcv3.firebasestorage.app',
    measurementId: 'G-V84R9GPYGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qiFxFltZwyjRLyHVzcXWI7jbweu5E2A',
    appId: '1:239580414059:android:c89582713d45db6336312e',
    messagingSenderId: '239580414059',
    projectId: 'miupcv3',
    storageBucket: 'miupcv3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDHr2WHaintdCLoodVAbmYhfKpANAt2XE',
    appId: '1:239580414059:ios:13f638357194537736312e',
    messagingSenderId: '239580414059',
    projectId: 'miupcv3',
    storageBucket: 'miupcv3.firebasestorage.app',
    iosBundleId: 'mmeo.system.pne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDHr2WHaintdCLoodVAbmYhfKpANAt2XE',
    appId: '1:239580414059:ios:13f638357194537736312e',
    messagingSenderId: '239580414059',
    projectId: 'miupcv3',
    storageBucket: 'miupcv3.firebasestorage.app',
    iosBundleId: 'mmeo.system.pne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsZimENmiHF1BqdNvbOxuNjETSWH7GOcw',
    appId: '1:239580414059:web:1922b8081b187cef36312e',
    messagingSenderId: '239580414059',
    projectId: 'miupcv3',
    authDomain: 'miupcv3.firebaseapp.com',
    storageBucket: 'miupcv3.firebasestorage.app',
    measurementId: 'G-PN1509YK4R',
  );

}